In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('dataset.csv')

In [4]:
df.sample(10, random_state=23)

,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description,Value
701714,813100,"Meal, Soybean",HO,Honduras,1978,2006,6,125,Domestic Consumption,8,(1000 MT),10.0
882243,452000,Oats,AR,Argentina,2020,2020,12,4,Area Harvested,4,(1000 HA),285.0
582789,813300,"Meal, Cottonseed",UZ,Uzbekistan,1992,2006,6,149,Food Use Dom. Cons.,8,(1000 MT),0.0
13678,11000,"Animal Numbers, Cattle",CA,Canada,2018,2020,10,176,Ending Stocks,5,(1000 HEAD),11480.0
136250,430000,Barley,NO,Norway,1987,2006,7,192,FSI Consumption,8,(1000 MT),68.0
444314,230000,"Dairy, Butter",VE,Venezuela,1968,1967,0,57,Imports,8,(1000 MT),0.0
1122020,4232000,"Oil, Soybean",FR,France,1966,2006,6,140,Industrial Dom. Cons.,8,(1000 MT),0.0
116543,430000,Barley,E2,EU-15,1968,2006,7,178,Total Distribution,8,(1000 MT),46631.0
1322681,2222000,"Oilseed, Soybean",BE,Belgium-Luxembourg,1988,2006,6,57,Imports,8,(1000 MT),1104.0
1145845,4232000,"Oil, Soybean",SG,Senegal,1978,2006,6,181,"Extr. Rate, 999.9999",23,(PERCENT),0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1893873 entries, 0 to 1893872
Data columns (total 12 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Commodity_Code         int64
 1   Commodity_Description  object
 2   Country_Code           object
 3   Country_Name           object
 4   Market_Year            int64
 5   Calendar_Year          int64
 6   Month                  int64
 7   Attribute_ID           int64
 8   Attribute_Description  object
 9   Unit_ID                int64
 10  Unit_Description       object
 11  Value                  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 173.4+ MB

In [6]:
df.describe()

,Commodity_Code,Market_Year,Calendar_Year,Month,Attribute_ID,Unit_ID,Value
count,1.893873e+06,1.893873e+06,1.893873e+06,1.893873e+06,1.893873e+06,1.893873e+06,1.893873e+06
mean,1.339019e+06,1.992388e+03,2.005487e+03,5.553296e+00,1.025964e+02,9.832787e+00,1.193542e+04
std,1.397169e+06,1.658725e+01,1.287997e+01,3.373824e+00,6.011163e+01,6.092073e+00,3.105539e+05
min,1.100000e+04,1.960000e+03,1.959000e+03,0.000000e+00,4.000000e+00,2.000000e+00,-9.510000e+03
25%,4.300000e+05,1.979000e+03,2.006000e+03,4.000000e+00,5.700000e+01,8.000000e+00,0.000000e+00
50%,6.120000e+05,1.992000e+03,2.006000e+03,6.000000e+00,8.800000e+01,8.000000e+00,1.500000e+01
75%,2.223000e+06,2.007000e+03,2.014000e+03,7.000000e+00,1.610000e+02,8.000000e+00,2.120000e+02
max,4.244000e+06,2.021000e+03,2.020000e+03,1.200000e+01,2.210000e+02,2.900000e+01,4.252870e+07

In [7]:
df.isnull().sum()

Commodity_Code              0
Commodity_Description       0
Country_Code             1004
Country_Name                0
Market_Year                 0
Calendar_Year               0
Month                       0
Attribute_ID                0
Attribute_Description       0
Unit_ID                     0
Unit_Description            0
Value                       0
dtype: int64

In [8]:

print(df[df['Country_Code'].isnull()][['Country_Name', 'Country_Code']])

                 Country_Name Country_Code
716454   Netherlands Antilles          NaN
716455   Netherlands Antilles          NaN
716456   Netherlands Antilles          NaN
716457   Netherlands Antilles          NaN
716458   Netherlands Antilles          NaN
...                       ...          ...
1725048  Netherlands Antilles          NaN
1725049  Netherlands Antilles          NaN
1725050  Netherlands Antilles          NaN
1725051  Netherlands Antilles          NaN
1725052  Netherlands Antilles          NaN

[1004 rows x 2 columns]

In [9]:
if 'NeA' not in df['Country_Code'].values:
    df.loc[(df['Country_Name'] == 'Netherlands Antilles') & (df['Country_Code'].isnull()), 'Country_Code'] = 'NeA'

In [10]:
df.isnull().sum()

Commodity_Code           0
Commodity_Description    0
Country_Code             0
Country_Name             0
Market_Year              0
Calendar_Year            0
Month                    0
Attribute_ID             0
Attribute_Description    0
Unit_ID                  0
Unit_Description         0
Value                    0
dtype: int64

In [11]:
# Columns to check
columns = ['Market_Year', 'Calendar_Year', 'Month', 'Value']

# Display min and max for each column
for col in columns:
    if col in df.columns:
        print(f"{col}:")
        print(f"  Min: {df[col].min()}")
        print(f"  Max: {df[col].max()}")
        print("-" * 30)
    else:
        print(f"Column '{col}' not found in the dataset.\n")

Market_Year:
  Min: 1960
  Max: 2021
------------------------------
Calendar_Year:
  Min: 1959
  Max: 2020
------------------------------
Month:
  Min: 0
  Max: 12
------------------------------
Value:
  Min: -9510.0
  Max: 42528700.0
------------------------------

In [15]:
df[df['Value']<=0]

,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description,Value
0,577400,"Almonds, Shelled Basis",AF,Afghanistan,2010,2018,10,20,Beginning Stocks,21,(MT),0.0
1,577400,"Almonds, Shelled Basis",AF,Afghanistan,2010,2018,10,125,Domestic Consumption,21,(MT),0.0
2,577400,"Almonds, Shelled Basis",AF,Afghanistan,2010,2018,10,176,Ending Stocks,21,(MT),0.0
3,577400,"Almonds, Shelled Basis",AF,Afghanistan,2010,2018,10,88,Exports,21,(MT),0.0
4,577400,"Almonds, Shelled Basis",AF,Afghanistan,2010,2018,10,57,Imports,21,(MT),0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1893855,410000,Wheat,RH,Zimbabwe,2019,2020,10,84,TY Imp. from U.S.,8,(1000 MT),0.0
1893862,410000,Wheat,RH,Zimbabwe,2020,2020,12,88,Exports,8,(1000 MT),0.0
1893863,410000,Wheat,RH,Zimbabwe,2020,2020,12,130,Feed Dom. Consumption,8,(1000 MT),0.0
1893869,410000,Wheat,RH,Zimbabwe,2020,2020,12,113,TY Exports,8,(1000 MT),0.0
1893870,410000,Wheat,RH,Zimbabwe,2020,2020,12,84,TY Imp. from U.S.,8,(1000 MT),0.0

In [18]:
df=df[df['Value']>0]
df.reset_index(inplace=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250186 entries, 0 to 1250185
Data columns (total 13 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   index                  1250186 non-null  int64
 1   Commodity_Code         1250186 non-null  int64
 2   Commodity_Description  1250186 non-null  object
 3   Country_Code           1250186 non-null  object
 4   Country_Name           1250186 non-null  object
 5   Market_Year            1250186 non-null  int64
 6   Calendar_Year          1250186 non-null  int64
 7   Month                  1250186 non-null  int64
 8   Attribute_ID           1250186 non-null  int64
 9   Attribute_Description  1250186 non-null  object
 10  Unit_ID                1250186 non-null  int64
 11  Unit_Description       1250186 non-null  object
 12  Value                  1250186 non-null  float64
dtypes: float64(1), int64(7), object(5)
memory usage: 124.0+ MB

In [25]:
df[df['Month']<1].sample(20)

,index,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description,Value
308609,445633,240000,"Dairy, Cheese",AS,Australia,1987,1986,0,20,Beginning Stocks,8,(1000 MT),81.0
529063,778036,111000,"Meat, Beef and Veal",GT,Guatemala,1970,1970,0,125,Domestic Consumption,7,(1000 MT CWE),40.0
1131199,1720731,612000,"Sugar, Centrifugal",MG,Mongolia,1990,1989,0,178,Total Distribution,8,(1000 MT),52.0
535435,786949,111000,"Meat, Beef and Veal",PN,Panama,1976,1976,0,88,Exports,7,(1000 MT CWE),3.0
1109351,1683842,612000,"Sugar, Centrifugal",GG,Georgia,1990,1989,0,139,Human Dom. Consumption,8,(1000 MT),180.0
10285,15218,11000,"Animal Numbers, Cattle",CO,Colombia,1995,1995,0,176,Ending Stocks,5,(1000 HEAD),18478.0
359581,507757,572220,"Grapefruit, Fresh",GZ,Gaza Strip,1992,1993,0,135,Fresh Dom. Consumption,8,(1000 MT),2.0
352598,498841,224200,"Dairy, Milk, Nonfat Dry",MX,Mexico,1972,1971,0,20,Beginning Stocks,8,(1000 MT),7.0
1098852,1667644,612000,"Sugar, Centrifugal",IV,Cote d'Ivoire,1985,1984,0,86,Total Supply,8,(1000 MT),143.0
296599,431267,230000,"Dairy, Butter",BE,Belgium-Luxembourg,1972,1971,0,86,Total Supply,8,(1000 MT),143.0
1117733,1698315,612000,"Sugar, Centrifugal",IR,Iran,1992,1991,0,178,Total Distribution,8,(1000 MT),1720.0
12310,17808,11000,"Animal Numbers, Cattle",EG,Egypt,1989,1989,0,176,Ending Stocks,5,(1000 HEAD),6385.0
524821,772118,111000,"Meat, Beef and Veal",CO,Colombia,1971,1971,0,88,Exports,7,(1000 MT CWE),17.0
1089596,1652558,612000,"Sugar, Centrifugal",BX,Brunei,1998,1997,0,20,Beginning Stocks,8,(1000 MT),3.0
953175,1448396,114200,"Poultry, Meat, Broiler",SP,Spain,1969,1969,0,125,Domestic Consumption,8,(1000 MT),318.0
1091507,1655747,612000,"Sugar, Centrifugal",BY,Burundi,1991,1990,0,57,Imports,8,(1000 MT),2.0
325092,464912,224400,"Dairy, Dry Whole Milk Powder",NZ,New Zealand,1988,1987,0,125,Domestic Consumption,8,(1000 MT),45.0
1106296,1678876,612000,"Sugar, Centrifugal",FJ,Fiji,1972,1971,0,86,Total Supply,8,(1000 MT),324.0
1150316,1751787,612000,"Sugar, Centrifugal",NS,Suriname,1968,1967,0,178,Total Distribution,8,(1000 MT),18.0
1164054,1772862,612000,"Sugar, Centrifugal",ZA,Zambia,2001,2000,0,20,Beginning Stocks,8,(1000 MT),32.0

In [24]:
df['Commodity_Description'].unique()

array(['Almonds, Shelled Basis', 'Animal Numbers, Cattle',
       'Animal Numbers, Swine', 'Apples, Fresh', 'Barley',
       'Cherries (Sweet&Sour), Fresh', 'Coffee, Green', 'Corn', 'Cotton',
       'Dairy, Butter', 'Dairy, Cheese', 'Dairy, Dry Whole Milk Powder',
       'Dairy, Milk, Fluid', 'Dairy, Milk, Nonfat Dry',
       'Grapefruit, Fresh', 'Grapes, Fresh Table', 'Lemons/Limes, Fresh',
       'Meal, Copra', 'Meal, Cottonseed', 'Meal, Fish',
       'Meal, Palm Kernel', 'Meal, Peanut', 'Meal, Rapeseed',
       'Meal, Soybean', 'Meal, Soybean (Local)', 'Meal, Sunflowerseed',
       'Meat, Beef and Veal', 'Meat, Chicken', 'Meat, Swine', 'Millet',
       'Mixed Grain', 'Oats', 'Oil, Coconut', 'Oil, Cottonseed',
       'Oil, Olive', 'Oil, Palm', 'Oil, Palm Kernel', 'Oil, Peanut',
       'Oil, Rapeseed', 'Oil, Soybean', 'Oil, Soybean (Local)',
       'Oil, Sunflowerseed', 'Oilseed, Copra', 'Oilseed, Cottonseed',
       'Oilseed, Palm Kernel', 'Oilseed, Peanut', 'Oilseed, Rapeseed',
       'Oilseed, Soybean', 'Oilseed, Soybean (Local)',
       'Oilseed, Sunflowerseed', 'Orange Juice', 'Oranges, Fresh',
       'Peaches & Nectarines, Fresh', 'Pears, Fresh',
       'Pistachios, Inshell Basis', 'Poultry, Meat, Broiler',
       'Rice, Milled', 'Rye', 'Sorghum', 'Sugar, Centrifugal',
       'Tangerines/Mandarins, Fresh', 'Walnuts, Inshell Basis', 'Wheat'],
      dtype=object)

In [28]:
df['Commodity_Description'].nunique()

63

In [39]:
commodity_data=df['Commodity_Description'].value_counts()
commodity_data.head(10)

Commodity_Description
Sugar, Centrifugal    85687
Corn                  76171
Wheat                 76118
Rice, Milled          72347
Cotton                71058
Barley                41155
Coffee, Green         40060
Meal, Soybean         39379
Sorghum               36207
Oil, Soybean          35353
Name: count, dtype: int64

In [40]:
commodity_data.tail(10)

Commodity_Description
Almonds, Shelled Basis          4523
Walnuts, Inshell Basis          4395
Grapefruit, Fresh               4092
Cherries (Sweet&Sour), Fresh    3899
Orange Juice                    3781
Mixed Grain                     3246
Pistachios, Inshell Basis       3115
Oilseed, Soybean (Local)        1316
Meal, Soybean (Local)           1271
Oil, Soybean (Local)            1246
Name: count, dtype: int64

In [26]:
df['Attribute_Description'].unique()

array(['Domestic Consumption', 'Imports', 'Total Distribution',
       'Total Supply', 'Exports', 'Production', 'Ending Stocks',
       'Beginning Stocks', 'Beef Cows Beg. Stocks', 'Calf Slaughter',
       'Cow Slaughter', 'Cows Entering the Herd',
       'Dairy Cows Beg. Stocks', 'Loss and Residual', 'Total Slaughter',
       'Sow Beginning Stocks', 'Annual % Change Prod. To Sows',
       'Sow Slaughter', 'Commercial Production', 'Non-Comm. Production',
       'Withdrawal From Market', 'Area Harvested', 'FSI Consumption',
       'Yield', 'TY Imports', 'Feed Dom. Consumption', 'TY Exports',
       'TY Imp. from U.S.', 'Bean Imports', 'Rst,Ground Dom. Consum',
       'Soluble Dom. Cons.', 'Soluble Imports', 'Arabica Production',
       'Bean Exports', 'Robusta Production', 'Roast & Ground Imports',
       'Roast & Ground Exports', 'Soluble Exports', 'Other Production',
       'Stocks-to-Use', 'USE Dom. Consumption', 'Loss Dom. Consumption',
       'Total Use', 'Cows In Milk', 'Cows Milk Production',
       'Factory Use Consum.', 'Fluid Use Dom. Consum.',
       'Other Milk Production', 'Feed Use Dom. Consum.',
       'Fresh Dom. Consumption', 'For Processing', 'Crush',
       'Extr. Rate, 999.9999', 'Feed Waste Dom. Cons.', 'SME',
       'Food Use Dom. Cons.', 'Industrial Dom. Cons.',
       'Catch For Reduction', 'Annual % Change Per Cap. Cons.',
       'Seed to Lint Ratio', 'Milling Rate (.9999)', 'Rough Production',
       'Cane Sugar Production', 'Human Dom. Consumption', 'Raw Imports',
       'Total Disappearance', 'Beet Sugar Production',
       'Refined Imp.(Raw Val)', 'Refined Exp.(Raw Val)', 'Raw Exports',
       'Other Disappearance'], dtype=object)

In [27]:
df['Attribute_Description'].nunique()

71

In [35]:
da=df['Attribute_Description'].value_counts()
da.head(10)

Attribute_Description
Total Supply            141639
Total Distribution      141573
Domestic Consumption    122751
Production              113619
Imports                  92127
Ending Stocks            65644
Beginning Stocks         64734
Exports                  63486
Yield                    46085
Area Harvested           44886
Name: count, dtype: int64

In [51]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

# Remove invalid or missing values
df = df.dropna(subset=['Value', 'Country_Name', 'Attribute_Description'])

# Create dropdown options
country_list = sorted(df['Country_Name'].unique())
attribute_list = sorted(df['Attribute_Description'].unique())

# Create dropdown widgets
country_dropdown = widgets.Dropdown(
    options=country_list,
    description='Country:',
    layout=widgets.Layout(width='50%')
)

attribute_dropdown = widgets.Dropdown(
    options=attribute_list,
    description='Attribute:',
    layout=widgets.Layout(width='50%')
)

def show_table(selected_country, selected_attribute):
    clear_output(wait=True)
    display(country_dropdown, attribute_dropdown)

    # Filter dataset
    filtered_df = df[
        (df['Country_Name'] == selected_country) &
        (df['Attribute_Description'] == selected_attribute) &
        (df['Value'] > 0)
    ]

    if filtered_df.empty:
        print("No data available for this selection.")
        return

    # Group by Commodity and Unit, sum the values
    grouped = filtered_df.groupby(
        ['Commodity_Description', 'Unit_Description'], as_index=False
    )['Value'].sum()

    # Sort for better display
    grouped = grouped.sort_values('Commodity_Description')

    display(grouped.reset_index(drop=True))

# Link widgets to function
out = widgets.interactive_output(show_table, {
    'selected_country': country_dropdown,
    'selected_attribute': attribute_dropdown
})

display(country_dropdown, attribute_dropdown, out)

Dropdown(description='Country:', layout=Layout(width='50%'), options=('Afghanistan', 'Albania', 'Algeria', 'An…

Dropdown(description='Attribute:', layout=Layout(width='50%'), options=('Annual % Change Per Cap. Cons.', 'Ann…

Output()

In [50]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output



# Drop missing or invalid values
df = df.dropna(subset=['Value', 'Country_Name', 'Attribute_Description', 'Commodity_Description', 'Unit_Description'])

# Dropdowns
country_list = sorted(df['Country_Name'].unique())
attribute_list = sorted(df['Attribute_Description'].unique())

country_dropdown = widgets.Dropdown(options=country_list, description='Country:', layout=widgets.Layout(width='50%'))
attribute_dropdown = widgets.Dropdown(options=attribute_list, description='Attribute:', layout=widgets.Layout(width='50%'))

def show_summed_table(selected_country, selected_attribute):
    clear_output(wait=True)
    display(country_dropdown, attribute_dropdown)

    # Filter by country and attribute
    filtered_df = df[
        (df['Country_Name'] == selected_country) &
        (df['Attribute_Description'] == selected_attribute) &
        (df['Value'] > 0)
    ]

    if filtered_df.empty:
        print("No data available for this selection.")
        return

    # Group by Commodity and Unit, sum the Values
    grouped = filtered_df.groupby(['Commodity_Description', 'Unit_Description'], as_index=False)['Value'].sum()

    # Sort by Commodity for better display
    grouped = grouped.sort_values('Commodity_Description')

    display(grouped.reset_index(drop=True))

out = widgets.interactive_output(show_summed_table, {
    'selected_country': country_dropdown,
    'selected_attribute': attribute_dropdown
})

display(country_dropdown, attribute_dropdown, out)

Dropdown(description='Country:', layout=Layout(width='50%'), options=('Afghanistan', 'Albania', 'Algeria', 'An…

Dropdown(description='Attribute:', layout=Layout(width='50%'), options=('Annual % Change Per Cap. Cons.', 'Ann…

Output()

In [ ]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt

# Clean and prepare your data
df = df.dropna(subset=['Value', 'Country_Name', 'Commodity_Description', 'Attribute_Description', 'Unit_Description'])

# Unique country list
country_list = sorted(df['Country_Name'].unique())

# Create dropdown widgets
country_dropdown = widgets.Dropdown(
    options=country_list,
    description='Country:',
    layout=widgets.Layout(width='50%')
)

attribute_dropdown = widgets.Dropdown(
    options=[],  # Will be populated based on country
    description='Attribute:',
    layout=widgets.Layout(width='50%')
)

# Update attribute dropdown when country changes
def update_attributes(*args):
    selected_country = country_dropdown.value
    filtered_attributes = df[df['Country_Name'] == selected_country]['Attribute_Description'].unique()
    attribute_dropdown.options = sorted(filtered_attributes)

country_dropdown.observe(update_attributes, names='value')

# Function to format both percentage and absolute value in pie chart
def format_autopct(values):
    def my_autopct(pct):
        total = sum(values)
        val = int(round(pct * total / 100.0))
        return f'{pct:.1f}%\n({val:,})'
    return my_autopct

# Pie chart plotting function
def plot_pie(selected_country, selected_attribute):
    clear_output(wait=True)
    display(country_dropdown, attribute_dropdown)

    filtered_df = df[
        (df['Country_Name'] == selected_country) &
        (df['Attribute_Description'] == selected_attribute) &
        (df['Value'] > 0)
    ]

    if filtered_df.empty:
        print("No data available for this selection.")
        return

    # Units
    units = filtered_df['Unit_Description'].unique()
    units_str = ', '.join(units)

    # Group by Commodity
    pie_data = filtered_df.groupby('Commodity_Description')['Value'].sum()

    if pie_data.empty:
        print("No data to plot.")
        return

    # Pie plot
    plt.figure(figsize=(9, 9))
    plt.pie(
        pie_data,
        labels=pie_data.index,
        autopct=format_autopct(pie_data.values),
        startangle=140
    )
    plt.title(f'Value by Commodity\nCountry: {selected_country}, Attribute: {selected_attribute}\nUnit(s): {units_str}')
    plt.tight_layout()
    plt.show()

# Interactive output
out = widgets.interactive_output(plot_pie, {
    'selected_country': country_dropdown,
    'selected_attribute': attribute_dropdown
})

# Initialize attribute options
update_attributes()

# Display UI
display(country_dropdown, attribute_dropdown, out)

Dropdown(description='Country:', layout=Layout(width='50%'), options=('Afghanistan', 'Albania', 'Algeria', 'An…

Dropdown(description='Attribute:', layout=Layout(width='50%'), options=('Area Harvested', 'Beet Sugar Producti…

Output()

In [ ]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt

# Clean and prepare your data
df = df.dropna(subset=['Value', 'Country_Name', 'Commodity_Description', 'Attribute_Description', 'Unit_Description'])

# Unique country list
country_list = sorted(df['Country_Name'].unique())

# Create widgets
country_dropdown = widgets.Dropdown(
    options=country_list,
    description='Country:',
    layout=widgets.Layout(width='50%')
)

commodity_dropdown = widgets.Dropdown(
    options=[],  # Will be dynamically updated
    description='Commodity:',
    layout=widgets.Layout(width='50%')
)

# Update commodity dropdown based on selected country
def update_commodities(*args):
    selected_country = country_dropdown.value
    filtered_commodities = df[df['Country_Name'] == selected_country]['Commodity_Description'].unique()
    commodity_dropdown.options = sorted(filtered_commodities)

country_dropdown.observe(update_commodities, names='value')

# Format function for pie chart values
def format_autopct(values):
    def my_autopct(pct):
        total = sum(values)
        val = int(round(pct * total / 100.0))
        return f'{pct:.1f}%\n({val:,})'
    return my_autopct

# Plotting function
def plot_pie(selected_country, selected_commodity):
    clear_output(wait=True)
    display(country_dropdown, commodity_dropdown)

    # Filter dataframe
    filtered_df = df[
        (df['Country_Name'] == selected_country) &
        (df['Commodity_Description'] == selected_commodity) &
        (df['Value'] > 0)
    ]

    if filtered_df.empty:
        print("No data available for this selection.")
        return

    # Get unique units
    units = filtered_df['Unit_Description'].unique()
    units_str = ', '.join(units)

    # Group by attribute and sum values
    pie_data = filtered_df.groupby('Attribute_Description')['Value'].sum()

    if pie_data.empty:
        print("No data to plot.")
        return

    # Plot pie chart
    plt.figure(figsize=(9, 9))
    plt.pie(
        pie_data,
        labels=pie_data.index,
        autopct=format_autopct(pie_data.values),
        startangle=140
    )
    plt.title(f'Value by Attribute\nCountry: {selected_country}, Commodity: {selected_commodity}\nUnit(s): {units_str}')
    plt.tight_layout()
    plt.show()

# Interactive output
out = widgets.interactive_output(plot_pie, {
    'selected_country': country_dropdown,
    'selected_commodity': commodity_dropdown
})

# Initialize dropdowns
update_commodities()

# Display interface
display(country_dropdown, commodity_dropdown, out)

Dropdown(description='Country:', layout=Layout(width='50%'), options=('Afghanistan', 'Albania', 'Algeria', 'An…

Dropdown(description='Commodity:', layout=Layout(width='50%'), options=('Apples, Fresh', 'Barley', 'Corn', 'Co…

Output()

In [ ]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt

# Clean data
df = df.dropna(subset=['Value', 'Country_Name', 'Commodity_Description', 'Unit_Description'])

# Unique commodity list
commodity_list = sorted(df['Commodity_Description'].unique())

# Dropdown for commodity selection
commodity_dropdown = widgets.Dropdown(
    options=commodity_list,
    description='Commodity:',
    layout=widgets.Layout(width='50%')
)

# Plotting function
def plot_pie_and_table(selected_commodity):
    clear_output(wait=True)
    display(commodity_dropdown)

    # Filter data
    filtered_df = df[
        (df['Commodity_Description'] == selected_commodity) &
        (df['Value'] > 0)
    ]

    if filtered_df.empty:
        print("No data available for this selection.")
        return

    # Aggregate by country
    group = filtered_df.groupby('Country_Name')['Value'].sum().sort_values(ascending=False)
    total = group.sum()

    # Compute percentage and prepare table
    table_df = pd.DataFrame({
        'Country': group.index,
        'Value': group.values,
        'Percentage': (group.values / total) * 100
    }).round({'Percentage': 2})

    # Show the table
    display(table_df.style.set_caption(f"Country-wise Distribution for '{selected_commodity}'")
            .format({'Value': '{:,.0f}', 'Percentage': '{:.2f}%'}))

    # Get units
    units = filtered_df['Unit_Description'].unique()
    units_str = ', '.join(units)

    # Pie chart
    plt.figure(figsize=(8, 8))
    plt.pie(group.values, labels=group.index, startangle=140)
    plt.title(f'{selected_commodity} Production by Country\nUnit(s): {units_str}')
    plt.tight_layout()
    plt.show()

# Create interactive output
out = widgets.interactive_output(plot_pie_and_table, {
    'selected_commodity': commodity_dropdown
})

# Display UI
display(commodity_dropdown, out)

Dropdown(description='Commodity:', layout=Layout(width='50%'), options=('Almonds, Shelled Basis', 'Animal Numb…

Output()

In [61]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt

# Clean data
df = df.dropna(subset=['Value', 'Country_Name', 'Attribute_Description', 'Unit_Description'])

# Get unique attribute list
attribute_list = sorted(df['Attribute_Description'].unique())

# Create dropdown for Attribute
attribute_dropdown = widgets.Dropdown(
    options=attribute_list,
    description='Attribute:',
    layout=widgets.Layout(width='50%')
)

# Plotting function
def plot_pie_and_table_by_attribute(selected_attribute):
    clear_output(wait=True)
    display(attribute_dropdown)

    # Filter the data
    filtered_df = df[
        (df['Attribute_Description'] == selected_attribute) &
        (df['Value'] > 0)
    ]

    if filtered_df.empty:
        print("No data available for this attribute.")
        return

    # Aggregate values by country
    group = filtered_df.groupby('Country_Name')['Value'].sum().sort_values(ascending=False)
    total = group.sum()

    # Create table with percentage
    table_df = pd.DataFrame({
        'Country': group.index,
        'Value': group.values,
        'Percentage': (group.values / total) * 100
    }).round({'Percentage': 2})

    # Display the table
    display(table_df.style.set_caption(f"Country-wise Distribution for '{selected_attribute}'")
            .format({'Value': '{:,.0f}', 'Percentage': '{:.2f}%'}))

    # Get units used
    units = filtered_df['Unit_Description'].unique()
    units_str = ', '.join(units)

    # Plot pie chart
    plt.figure(figsize=(8, 8))
    plt.pie(group.values, labels=group.index, startangle=140)
    plt.title(f"{selected_attribute} by Country\nUnit(s): {units_str}")
    plt.tight_layout()
    plt.show()

# Link the dropdown with the plotting function
out = widgets.interactive_output(plot_pie_and_table_by_attribute, {
    'selected_attribute': attribute_dropdown
})

# Display the widget and output
display(attribute_dropdown, out)

Dropdown(description='Attribute:', layout=Layout(width='50%'), options=('Annual % Change Per Cap. Cons.', 'Ann…

Output()

In [ ]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt

# Clean and prepare data
df = df.dropna(subset=['Value', 'Country_Name', 'Commodity_Description',
                       'Attribute_Description', 'Market_Year', 'Unit_Description'])
df['Market_Year'] = df['Market_Year'].astype(int)

# Create initial dropdowns
commodity_list = sorted(df['Commodity_Description'].unique())
commodity_dropdown = widgets.Dropdown(
    options=commodity_list,
    description='Commodity:',
    layout=widgets.Layout(width='45%')
)

attribute_dropdown = widgets.Dropdown(
    options=[],  # Will update dynamically
    description='Attribute:',
    layout=widgets.Layout(width='45%')
)

# Update attribute options based on selected commodity
def update_attribute_options(*args):
    selected_commodity = commodity_dropdown.value
    if selected_commodity:
        filtered_attrs = df[df['Commodity_Description'] == selected_commodity]['Attribute_Description'].unique()
        attribute_dropdown.options = sorted(filtered_attrs)

commodity_dropdown.observe(update_attribute_options, names='value')
update_attribute_options()  # initial fill

# Plotting function
def plot_line_chart(selected_commodity, selected_attribute):
    clear_output(wait=True)
    display(commodity_dropdown, attribute_dropdown)

    filtered_df = df[
        (df['Commodity_Description'] == selected_commodity) &
        (df['Attribute_Description'] == selected_attribute) &
        (df['Value'] > 0)
    ]

    if filtered_df.empty:
        print("No data available for this selection.")
        return

    # Calculate top 10 countries by total Value
    top_countries = (
        filtered_df.groupby('Country_Name')['Value']
        .sum()
        .sort_values(ascending=False)
        .head(10)
        .index
    )

    # Filter again for only top countries
    top_df = filtered_df[filtered_df['Country_Name'].isin(top_countries)]

    # Group and pivot
    grouped = top_df.groupby(['Market_Year', 'Country_Name'])['Value'].sum().reset_index()
    pivot_df = grouped.pivot(index='Market_Year', columns='Country_Name', values='Value').fillna(0)

    # Get unit(s)
    units = top_df['Unit_Description'].unique()
    unit_str = ', '.join(units)

    # Plot
    plt.figure(figsize=(12, 6))
    for country in pivot_df.columns:
        plt.plot(pivot_df.index, pivot_df[country], label=country)

    plt.title(f"{selected_attribute} of {selected_commodity} by Top 10 Producing Countries Over Years\nUnit(s): {unit_str}")
    plt.xlabel("Market Year")
    plt.ylabel(f"Value ({unit_str})")
    plt.legend(title='Country', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Interactive output
out = widgets.interactive_output(plot_line_chart, {
    'selected_commodity': commodity_dropdown,
    'selected_attribute': attribute_dropdown
})

# Display widgets and output
display(commodity_dropdown, attribute_dropdown, out)

Dropdown(description='Commodity:', layout=Layout(width='45%'), options=('Almonds, Shelled Basis', 'Animal Numb…

Dropdown(description='Attribute:', layout=Layout(width='45%'), options=('Beginning Stocks', 'Domestic Consumpt…

Output()

In [66]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt
import seaborn as sns

# Clean data
df = df.dropna(subset=['Value', 'Country_Name', 'Commodity_Description',
                       'Attribute_Description', 'Market_Year', 'Unit_Description'])
df['Market_Year'] = df['Market_Year'].astype(int)

# Dropdown for Commodity
commodity_list = sorted(df['Commodity_Description'].unique())
commodity_dropdown = widgets.Dropdown(
    options=commodity_list,
    description='Commodity:',
    layout=widgets.Layout(width='45%')
)

# Dropdown for Attribute (initially empty; will update dynamically)
attribute_dropdown = widgets.Dropdown(
    options=[],
    description='Attribute:',
    layout=widgets.Layout(width='45%')
)

# Function to update attribute options when commodity changes
def update_attribute_options(*args):
    selected_commodity = commodity_dropdown.value
    if selected_commodity:
        attrs = df[df['Commodity_Description'] == selected_commodity]['Attribute_Description'].unique()
        attribute_dropdown.options = sorted(attrs)
    else:
        attribute_dropdown.options = []

# Link the update function to commodity dropdown value changes
commodity_dropdown.observe(update_attribute_options, names='value')

# Initialize attribute dropdown options
update_attribute_options()

def plot_scatter(selected_commodity, selected_attribute):
    clear_output(wait=True)
    display(commodity_dropdown, attribute_dropdown)
    
    filtered_df = df[
        (df['Commodity_Description'] == selected_commodity) &
        (df['Attribute_Description'] == selected_attribute) &
        (df['Value'] > 0)
    ]

    if filtered_df.empty:
        print("No data available for this selection.")
        return

    units = filtered_df['Unit_Description'].unique()
    unit_str = ', '.join(units)

    plt.figure(figsize=(12, 6))
    sns.scatterplot(
        data=filtered_df,
        x='Market_Year',
        y='Value',
        hue='Country_Name',
        palette='tab10',
        alpha=0.7
    )
    plt.title(f'Scatter Plot of {selected_attribute} for {selected_commodity} Over Market Years\nUnit(s): {unit_str}')
    plt.xlabel('Market Year')
    plt.ylabel(f'Value ({unit_str})')
    plt.legend(title='Country', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

out = widgets.interactive_output(plot_scatter, {
    'selected_commodity': commodity_dropdown,
    'selected_attribute': attribute_dropdown
})

display(commodity_dropdown, attribute_dropdown, out)

Dropdown(description='Commodity:', layout=Layout(width='45%'), options=('Almonds, Shelled Basis', 'Animal Numb…

Dropdown(description='Attribute:', layout=Layout(width='45%'), options=('Beginning Stocks', 'Domestic Consumpt…

Output()

In [ ]:
import pandas as pd
import numpy as np
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Clean data
df = df.dropna(subset=['Value', 'Country_Name', 'Commodity_Description',
                       'Attribute_Description', 'Market_Year', 'Month'])
df['Market_Year'] = df['Market_Year'].astype(int)
df['Month'] = df['Month'].astype(int)

# Dropdown options
country_list = sorted(df['Country_Name'].unique())
commodity_list = sorted(df['Commodity_Description'].unique())
attribute_list = sorted(df['Attribute_Description'].unique())

country_dropdown = widgets.Dropdown(options=country_list, description='Country:', layout=widgets.Layout(width='40%'))
commodity_dropdown = widgets.Dropdown(options=commodity_list, description='Commodity:', layout=widgets.Layout(width='40%'))
attribute_dropdown = widgets.Dropdown(options=attribute_list, description='Attribute:', layout=widgets.Layout(width='40%'))

def regression_predict(selected_country, selected_commodity, selected_attribute):
    clear_output(wait=True)
    display(country_dropdown, commodity_dropdown, attribute_dropdown)

    # Filter data by selections
    data = df[(df['Country_Name'] == selected_country) &
              (df['Commodity_Description'] == selected_commodity) &
              (df['Attribute_Description'] == selected_attribute) &
              (df['Value'] > 0)]
    
    if data.empty:
        print("No data available for this selection.")
        return

    # Prepare features and target
    X = data[['Market_Year', 'Month']]
    y = data['Value']

    # One-hot encode categorical variables - for simplicity here we don't include categorical as features
    # because we already filter by them; but if needed, you can include more features.

    # Split train/test by year (e.g. last 20% years as test)
    years = sorted(data['Market_Year'].unique())
    if len(years) < 3:
        print("Not enough years of data for training.")
        return
    train_years = years[:int(len(years)*0.8)]
    test_years = years[int(len(years)*0.8):]

    train_mask = data['Market_Year'].isin(train_years)
    test_mask = data['Market_Year'].isin(test_years)

    X_train = X[train_mask]
    y_train = y[train_mask]
    X_test = X[test_mask]
    y_test = y[test_mask]

    # Model
    model = RandomForestRegressor(random_state=42, n_estimators=100)
    model.fit(X_train, y_train)

    # Predict test
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)

    # Predict next 5 years (using all months 1-12)
    last_year = max(years)
    future_years = np.repeat(np.arange(last_year+1, last_year+6), 12)
    future_months = np.tile(np.arange(1, 13), 5)
    future_X = pd.DataFrame({'Market_Year': future_years, 'Month': future_months})
    future_pred = model.predict(future_X)

    # Plot results
    plt.figure(figsize=(14,6))

    # Actual train + test
    plt.plot(data['Market_Year'].astype(str) + '-' + data['Month'].astype(str).str.zfill(2), data['Value'], label='Actual', marker='o')

    # Predicted test
    test_dates = X_test['Market_Year'].astype(str) + '-' + X_test['Month'].astype(str).str.zfill(2)
    plt.scatter(test_dates, y_pred, color='orange', label='Predicted (Test)', marker='x')

    # Future predictions
    future_dates = future_X['Market_Year'].astype(str) + '-' + future_X['Month'].astype(str).str.zfill(2)
    plt.plot(future_dates, future_pred, label='Predicted (Future)', linestyle='--')

    plt.xticks(rotation=90)
    plt.ylabel('Production Value')
    plt.title(f'Production Value Prediction for {selected_commodity} in {selected_country}\nAttribute: {selected_attribute}\nMAE on test set: {mae:.2f}')
    plt.legend()
    plt.tight_layout()
    plt.show()

# Link widgets and function
out = widgets.interactive_output(regression_predict, {
    'selected_country': country_dropdown,
    'selected_commodity': commodity_dropdown,
    'selected_attribute': attribute_dropdown
})

display(country_dropdown, commodity_dropdown, attribute_dropdown, out)

Dropdown(description='Country:', layout=Layout(width='40%'), options=('Afghanistan', 'Albania', 'Algeria', 'An…

Dropdown(description='Commodity:', layout=Layout(width='40%'), options=('Almonds, Shelled Basis', 'Animal Numb…

Dropdown(description='Attribute:', layout=Layout(width='40%'), options=('Annual % Change Per Cap. Cons.', 'Ann…

Output()